window.REVISTA_DATA = {
  edicion: {
    numero: 1,
    mes: "Septiembre",
    anio: 2026,
    titulo: "Libros, paseo y el Km 30",
    bajada:
      "La 7ª Feria del Libro de Malvinas, el Paseo Ferial junto a la estación y una guía de comercios reales de Rosario y Derqui.",
    fecha: "11 de septiembre de 2026",
    portadaTema: "primavera",
  },

  nav: [
    { href: "index.html", label: "Inicio", page: "home" },
    { href: "edicion.html", label: "Edición", page: "edicion" },
    { href: "actualidad.html", label: "Actualidad", page: "actualidad" },
    { href: "comercios.html", label: "Comercios", page: "comercios" },
    { href: "profesionales.html", label: "Profesionales", page: "profesionales" },
    { href: "clasificados.html", label: "Clasificados", page: "clasificados" },
    { href: "eventos.html", label: "Agenda", page: "eventos" },
    { href: "anunciantes.html", label: "Anunciantes", page: "anunciantes" },
    { href: "recibir.html", label: "Recibir", page: "recibir" },
    { href: "difundir.html", label: "Difundir", page: "difundir" },
  ],

  secciones: [
    {
      id: "actualidad",
      nombre: "Actualidad",
      desc: "Lo que pasa en Sourdeaux y Malvinas Argentinas.",
      href: "actualidad.html",
    },
    {
      id: "barrio",
      nombre: "Barrio",
      desc: "Historias, vecinos y memoria del Km 30.",
      href: "actualidad.html#barrio",
    },
    {
      id: "comercios",
      nombre: "Comercios",
      desc: "Guía de negocios para comprar cerca.",
      href: "comercios.html",
    },
    {
      id: "profesionales",
      nombre: "Profesionales",
      desc: "Salud, oficios y estudios del barrio.",
      href: "profesionales.html",
    },
    {
      id: "clasificados",
      nombre: "Clasificados",
      desc: "Avisos de vecinos, alquileres y servicios.",
      href: "clasificados.html",
    },
    {
      id: "eventos",
      nombre: "Agenda",
      desc: "Ferias, clubes, escuelas y cultura.",
      href: "eventos.html",
    },
  ],

  articulos: [
    {
      id: "feria-libro-malvinas-2026",
      seccion: "actualidad",
      kicker: "Portada · Edición 01",
      titulo: "Esta semana: la 7ª Feria del Libro de Malvinas Argentinas",
      bajada:
        "Del 11 al 20 de septiembre, junto al Palacio Municipal. Entrada libre. Desde Sourdeaux se llega por el Belgrano Norte y el 341.",
      cuerpo: [
        "Malvinas Argentinas abre su 7ª Feria del Libro entre el 11 y el 20 de septiembre, en las inmediaciones del Palacio Municipal, Av. Presidente Perón 4276. Lo organiza el Municipio con la Fundación El Libro. La entrada es libre y gratuita.",
        "Los horarios publicados por el municipio son de lunes a viernes de 9 a 20, y sábados, domingos y feriados de 12 a 21. Contarte Cultura anticipó más de 60 stands y una programación con autores como Darío Sztajnszrajber, Pedro Saborido, Florencia Canale y Reynaldo Sietecase. Los chicos que vayan con la escuela reciben un chequelibro para comprar en el predio.",
        "Para un vecino de Adolfo Sourdeaux el trayecto es corto: el Belgrano Norte deja en la estación del Km 30 y de ahí se conecta hacia Los Polvorines y el centro municipal. El 341 también recorre el partido.",
        "Esta edición de la revista sale el mismo día de la apertura. Si vas, llevá DNI, anotá los stands que te sirvan y, si tenés un comercio o un oficio en Rosario o Derqui, esta semana es buena para que el barrio te encuentre.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      portada: true,
      tiempo: "5 min",
    },
    {
      id: "paseo-ferial-estacion",
      seccion: "barrio",
      kicker: "Barrio",
      titulo: "El Paseo Ferial ya es la plaza de la estación",
      bajada:
        "Entre Derqui y Juan Madera hay 24 puestos, anfiteatro y luz LED. Funciona todos los días de 8 a 20, con rotación de emprendedores.",
      cuerpo: [
        "En octubre de 2025 el municipio inauguró el Paseo Ferial de Ing. Adolfo Sourdeaux. El recinto suma unos 400 metros cuadrados junto a la estación del Belgrano Norte, de Derqui a Juan Madera. Hay 24 puestos, sectores de descanso y un anfiteatro.",
        "El intendente Leonardo Nardini dijo entonces que el lugar no era solo un paseo iluminado: también daba salida laboral a casi 50 feriantes que rotan los puestos. Gabriela y Priscila, de Esencia Dulce, contaron que se anotaron por la convocatoria del CAM después de vender por WhatsApp. María Crochet, de Grand Bourg, lleva tejidos y clases.",
        "Antes, el municipio ya había pavimentado y peatonalizado Juárez Celman, Juan Madera y Gilardi, y había renovado la estación (andenes, LED, accesos y cámaras). El nombre oficial del barrio es Ingeniero Adolfo Sourdeaux; muchos vecinos siguen diciendo Km 30.",
        "Hoy el paseo abre todos los días de 8 a 20. Si organizás un evento o tenés un puesto, mandalo a la revista: la agenda se actualiza en la web.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      tiempo: "5 min",
    },
    {
      id: "guia-rosario-derqui",
      seccion: "comercios",
      kicker: "Comercios",
      titulo: "Rosario y Derqui, comercio por comercio",
      bajada:
        "Farmacia Álvarez, ferreterías de la estación, panadería del Km 30 y el hospital veterinario de Luis Espinosa. Datos tomados de sitios y guías públicas.",
      cuerpo: [
        "La costilla comercial de Sourdeaux sigue siendo Rosario, entre la estación y Derqui. En esta guía no inventamos fichas: cargamos comercios que figuran con dirección y, cuando existe, teléfono publicado.",
        "Farmacia Álvarez está en Rosario 4605 desde hace décadas. Su sitio propio publica obras sociales, dos líneas fijas (4748-1868 y 4748-0415) y WhatsApp 11 2889-6715. A pocos metros aparecen Ferretería Nasi (Rosario 4591) y Ferretería Bulonera Sourdeaux (Rosario 4635), esta última con horario extendido y delivery.",
        "Sobre Derqui, la Panadería La Nueva Km30 (Derqui 1331) abre de madrugada y Electricidad López (Derqui 1015) cubre materiales eléctricos. En Luis Espinosa 1760 funciona el Hospital Veterinario Adolfo Sourdeaux, con atención de semana y guardia de fin de semana.",
        "Si tu local está y no figura, o si un dato cambió, escribinos. La ficha se corrige una vez y viaja en cada edición.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      tiempo: "4 min",
    },
    {
      id: "salud-km30",
      seccion: "profesionales",
      kicker: "Profesionales",
      titulo: "Dónde atenderse en el Km 30: sanitaria, odontólogos y oficios",
      bajada:
        "La Unidad Sanitaria Km 30 está en Rosario. En la misma calle hay consultorios odontológicos. El buscador solo lista fichas con domicilio publicado.",
      cuerpo: [
        "La atención pública del barrio pasa por la Unidad Sanitaria Km 30 / Unidad Funcional Km 30, en Rosario 4472/4572, entre Portela y Rondeau. Es un centro municipal con atención diaria y especialidades. El municipio también readecuó el Centro de Salud ARA San Juan, en Rosario al 4400.",
        "En oficios del barrio está Servi-Net: redes, WiFi, fibra, servidores, cámaras y soporte de PC, con WhatsApp 11 4030-6408. En el casco también hay consultorios odontológicos con domicilio visible: Dental Ar Sourdeaux, Rosario 4680, y el Centro Odontológico Adriana Roel, Av. San Martín 319.",
        "Si atendés en Sourdeaux, Villa de Mayo o Los Polvorines, mandá tu ficha: nombre, matrícula, zona y WhatsApp.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: false,
      tiempo: "3 min",
    },
    {
      id: "agenda-septiembre",
      seccion: "eventos",
      kicker: "Agenda",
      titulo: "Qué hay para hacer: feria del libro, paseo y mercado itinerante",
      bajada:
        "Tres citas reales del distrito. El Paseo Ferial es todos los días; la Feria del Libro, esta quincena; Mercado Malvinas rota por las plazas.",
      cuerpo: [
        "La cita grande de septiembre es la Feria del Libro, del 11 al 20, junto al Palacio Municipal. El Paseo Ferial de Sourdeaux, en cambio, no es un evento de un día: abre de 8 a 20 junto a la estación, con puestos rotativos.",
        "Mercado Malvinas es una feria municipal de alimentos (almacén, lácteos, verdura y avícola) que se planta en Plaza Güemes, General Pico y Pío XII. En las últimas visitas publicadas funcionó de 9 a 14, con hasta 40% de descuento presentando DNI, y se suspende por lluvia. Las fechas cambian cada semana: hay que mirar el anuncio municipal.",
        "Si un club, una escuela o un salón tiene una fecha cerrada, mandala. No publicamos horarios inventados.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      tiempo: "3 min",
    },
    {
      id: "publicar-aviso",
      seccion: "actualidad",
      kicker: "Oficina",
      titulo: "Cómo entrar a la guía: un aviso que se reenvía",
      bajada:
        "La diferencia de un anuncio de barrio es que no se queda en una web: se manda por WhatsApp, por mail y queda en el mostrador.",
      cuerpo: [
        "Revista Adolfo Sourdeaux se arma para el celular del vecino. Cada ficha tiene dirección, horario y, si el comercio lo publica, un botón de WhatsApp o de llamada.",
        "Los paquetes van desde el clasificado de 40 palabras hasta la ficha destacada, el banner de portada y la mención en el envío de la edición.",
        "Para sumarte hace falta nombre, rubro, dirección y un teléfono. El resto lo armamos para que se vea como revista, no como un post suelto.",
      ],
      autor: "Comercial SOURDEAUX",
      destacado: false,
      tiempo: "3 min",
    },
  ],

  comercios: [
    {
      id: "servi-net-comercio",
      nombre: "Servi-Net",
      rubro: "Informática",
      dest: true,
      dir: "Adolfo Sourdeaux, Malvinas Argentinas",
      horario: "A domicilio y por WhatsApp",
      tel: "11 4030-6408",
      wa: "5491140306408",
      desc: "Redes, WiFi, fibra, servidores, cámaras y soporte de PC para casas y comercios del Km 30.",
    },
    {
      id: "farmacia-alvarez",
      nombre: "Farmacia Álvarez",
      rubro: "Salud",
      dest: true,
      dir: "Rosario 4605, Ing. Adolfo Sourdeaux",
      horario: "Consultá turno y horario en el local o por WhatsApp",
      tel: "11 4748-1868",
      wa: "5491128896715",
      desc: "Desde 1961. Obras sociales, medicamentos, perfumería y ortopedia. También 11 4748-0415.",
    },
    {
      id: "ferreteria-bulonera",
      nombre: "Ferretería Bulonera Sourdeaux",
      rubro: "Hogar y oficio",
      dest: true,
      dir: "Rosario 4635, Ing. Adolfo Sourdeaux",
      horario: "Lun a Sáb 8 a 20 · Dom 8 a 13",
      tel: "11 2417-2566",
      desc: "Ferretería y bulonería sobre Rosario. Delivery publicado. Conviene llamar antes si buscás un bulón puntual.",
    },
    {
      id: "ferreteria-nasi",
      nombre: "Ferretería Nasi",
      rubro: "Hogar y oficio",
      dest: false,
      dir: "Rosario 4591, Ing. Adolfo Sourdeaux",
      horario: "Lun a Vie 8:30 a 13 y 16 a 19 · Sáb 8:30 a 13",
      tel: "11 4748-9771",
      desc: "Herramientas y ferretería a metros de la estación, a nombre de Leonardo Santiago Nasi.",
    },
    {
      id: "electricidad-lopez",
      nombre: "Electricidad López",
      rubro: "Hogar y oficio",
      dest: true,
      dir: "Derqui 1015, Ing. Adolfo Sourdeaux",
      horario: "Lun a Vie 8:30 a 13 y 14:30 a 18:30 · Sáb 8:30 a 13",
      tel: "11 4741-4757",
      desc: "Materiales eléctricos sobre Derqui, a pocas cuadras de la estación.",
    },
    {
      id: "panaderia-km30",
      nombre: "Panadería La Nueva Km30",
      rubro: "Gastronomía",
      dest: true,
      dir: "Derqui 1331, Ing. Adolfo Sourdeaux",
      horario: "Lun a Sáb 6:30 a 20:30 · Dom 9:15 a 13 y 16:30 a 19",
      desc: "Panadería del casco, sobre Derqui. No hay teléfono público; se compra en el mostrador.",
    },
    {
      id: "pan-del-cielo",
      nombre: "Pan Del Cielo",
      rubro: "Gastronomía",
      dest: false,
      dir: "Rosario 4586, Ing. Adolfo Sourdeaux",
      horario: "Consultá horario en el local",
      desc: "Panadería sobre Rosario, frente al movimiento de la estación.",
    },
    {
      id: "hospital-veterinario",
      nombre: "Hospital Veterinario Adolfo Sourdeaux",
      rubro: "Mascotas",
      dest: true,
      dir: "Luis Espinosa 1760, Ing. Adolfo Sourdeaux",
      horario: "Lun a Vie 9 a 18 · Sáb y Dom 9 a 13",
      tel: "11 4748-9159",
      desc: "Clínica, imágenes e internación. El teléfono más repetido en las guías es 4748-9159.",
    },
    {
      id: "ferreteria-carti",
      nombre: "Ferretería Carti",
      rubro: "Hogar y oficio",
      dest: false,
      dir: "Luis Espinosa 1561, Ing. Adolfo Sourdeaux",
      horario: "Lun a Vie 8 a 14:30 y 15:30 a 19 · Sáb y Dom 8 a 18",
      tel: "11 4741-7900",
      desc: "Ferretería sobre Luis Espinosa, a la altura del hospital veterinario.",
    },
    {
      id: "sanitarios-lg",
      nombre: "Sanitarios LG",
      rubro: "Hogar y oficio",
      dest: false,
      dir: "Coronel Winter 4386, Ing. Adolfo Sourdeaux",
      horario: "Lun a Vie 8 a 13 y 14 a 18:30 · Sáb 8 a 16",
      tel: "11 4748-6187",
      desc: "Sanitarios y materiales para baño sobre Coronel Winter.",
    },
    {
      id: "ferreteria-la-curva",
      nombre: "Ferretería La Curva",
      rubro: "Hogar y oficio",
      dest: false,
      dir: "Viedma 4373, Ing. Adolfo Sourdeaux",
      horario: "Lun a Sáb 8:30 a 13 y 16:30 a 20 · Dom 9:30 a 13",
      tel: "11 4846-0527",
      desc: "Ferretería de barrio sobre Viedma.",
    },
    {
      id: "carniceria-amistad",
      nombre: "Carnicería La Amistad",
      rubro: "Almacén",
      dest: false,
      dir: "Coronel Winter, Ing. Adolfo Sourdeaux",
      horario: "Consultá horario en el local",
      tel: "11 2446-8211",
      desc: "Carnicería sobre Winter, con entrega en el día según las guías.",
    },
    {
      id: "vaquita-kennedy",
      nombre: "Vaquita",
      rubro: "Almacén",
      dest: false,
      dir: "J. F. Kennedy 4787, Ing. Adolfo Sourdeaux",
      horario: "Consultá horario en el local",
      tel: "11 4748-9803",
      desc: "Carnicería / almacén sobre Kennedy.",
    },
    {
      id: "tintos-peluqueria",
      nombre: "Tinto's Peluquería",
      rubro: "Belleza",
      dest: false,
      dir: "Rosario 4578, Ing. Adolfo Sourdeaux",
      horario: "Consultá horario en el local",
      desc: "Peluquería sobre Rosario, a metros de la estación. Sin teléfono publicado.",
    },
  ],

  profesionales: [
    {
      id: "servi-net",
      nombre: "Servi-Net",
      oficio: "Redes, informática y ciberseguridad",
      rubro: "Oficios",
      busca: "redes wifi camaras computadora informatica tecnico pc servidor ciberseguridad fibra router",
      dest: true,
      zona: "Adolfo Sourdeaux y Zona Norte",
      dir: "Atención a domicilio en el Km 30 y Malvinas Argentinas",
      mat: "servi-net.com.ar",
      tel: "11 4030-6408",
      wa: "5491140306408",
      desc: "Redes cableadas y WiFi, fibra, servidores, cámaras, reparación de PC y soporte para comercios. WhatsApp de la casa.",
    },
    {
      id: "dental-ar",
      nombre: "Dental Ar Sourdeaux",
      oficio: "Odontología integral",
      rubro: "Salud",
      busca: "dentista odontologo implante ortodoncia muelas",
      dest: true,
      zona: "Rosario, cerca de estación",
      dir: "Rosario 4680, Ing. Adolfo Sourdeaux",
      mat: "Consultorio",
      tel: "11 6206-3510",
      desc: "Cirugía, implantes, prótesis, endodoncia, ortodoncia y atención a niños. Lun, mar, jue y vie 10 a 19 · Sáb 10 a 18.",
    },
    {
      id: "adriana-roel",
      nombre: "Centro Odontológico Adriana Roel",
      oficio: "Odontología",
      rubro: "Salud",
      busca: "dentista odontologa",
      dest: true,
      zona: "Av. San Martín",
      dir: "Av. San Martín 319, Ing. Adolfo Sourdeaux",
      mat: "Consultorio",
      tel: "11 4748-4560",
      desc: "Consultorio odontológico con domicilio y teléfono publicados en directorios del barrio.",
    },
    {
      id: "unidad-km30",
      nombre: "Unidad Sanitaria Km 30",
      oficio: "Atención primaria municipal",
      rubro: "Salud",
      busca: "medico medica pediatra centro de salud vacuna",
      dest: true,
      zona: "Rosario",
      dir: "Rosario 4572 (e/ Portela y Rondeau), Ing. Adolfo Sourdeaux",
      mat: "Municipal",
      desc: "Centro de salud público con atención diaria y especialidades. También figura como Unidad Funcional Km 30 (Rosario 4472).",
    },
    {
      id: "centro-ara-san-juan",
      nombre: "Centro de Salud ARA San Juan",
      oficio: "Atención primaria municipal",
      rubro: "Salud",
      busca: "medico centro de salud",
      dest: false,
      zona: "Rosario al 4400",
      dir: "Rosario 4400, Ing. Adolfo Sourdeaux",
      mat: "Municipal",
      desc: "El municipio readecuó el edificio para reforzar la atención primaria. Consultá turnos en el centro.",
    },
  ],

  clasificados: [],

  eventos: [
    {
      id: "e1",
      fecha: "11 al 20 sep",
      hora: "Lun a Vie 9 a 20 · Sáb y Dom 12 a 21",
      titulo: "7ª Feria del Libro de Malvinas Argentinas",
      lugar: "Av. Pte. Perón 4276, Palacio Municipal",
      desc: "Entrada libre. Más de 60 stands, autores y chequelibro para escuelas. Municipio y Fundación El Libro.",
    },
    {
      id: "e2",
      fecha: "Todos los días",
      hora: "8 a 20",
      titulo: "Paseo Ferial de Ing. Adolfo Sourdeaux",
      lugar: "Derqui a Juan Madera, junto a la estación",
      desc: "24 puestos rotativos, anfiteatro y paseo peatonal. Emprendimientos locales.",
    },
    {
      id: "e3",
      fecha: "Itinerante",
      hora: "9 a 14 (se suspende por lluvia)",
      titulo: "Mercado Malvinas",
      lugar: "Cuando está en Sourdeaux: Plaza Güemes (Gral. Pico y Pío XII)",
      desc: "Almacén, lácteos, verdura y avícola. Hasta 40% con DNI. Las fechas las anuncia el municipio cada semana.",
    },
  ],

  paquetes: [
    {
      id: "clasificado",
      nombre: "Clasificado",
      precio: "Consultar",
      detalle: "40 palabras + teléfono. Sale en la web y en el envío de la edición.",
      items: ["Texto breve", "Una categoría", "Link de WhatsApp", "Vigencia 15 días"],
    },
    {
      id: "ficha",
      nombre: "Ficha comercio o profesional",
      precio: "Consultar",
      detalle: "Tu tarjeta permanente en el buscador, con dirección y contacto.",
      items: ["Nombre y rubro", "Dirección y horario", "Botón de WhatsApp o llamada", "Aparece en búsquedas"],
    },
    {
      id: "destacado",
      nombre: "Destacado de edición",
      precio: "Consultar",
      detalle: "Lugar fijo en portada o en la página de la sección durante un mes.",
      items: ["Recuadro editorial", "Mención en el mail", "Prioridad en el listado", "Diseño incluido"],
    },
    {
      id: "portada",
      nombre: "Banner de portada",
      precio: "Consultar",
      detalle: "Hay tres lugares de portada por edición. El primero es el banner ancho; los otros dos van al lado, en home, edición y mail.",
      items: ["Hasta 3 avisos de portada", "Home + edición", "Envío WhatsApp", "Reporte de clics"],
    },
    {
      id: "seccion",
      nombre: "Banner de sección",
      precio: "Consultar",
      detalle: "Un aviso propio en Actualidad, Comercios, Profesionales, Clasificados o Agenda.",
      items: ["Página de la sección", "Mención en la edición", "Formato revista", "Diseño incluido"],
    },
  ],

  anunciantes: [
    { nombre: "Servi-Net", rubro: "Informática y redes", tipo: "Portada 1" },
    { nombre: "Farmacia Álvarez", rubro: "Salud", tipo: "Portada 2 · Ejemplo" },
    { nombre: "Espacio disponible", rubro: "Tu comercio en tapa", tipo: "Portada 3" },
    { nombre: "Hospital Veterinario Adolfo Sourdeaux", rubro: "Mascotas", tipo: "Actualidad · Ejemplo" },
    { nombre: "Ferretería Bulonera Sourdeaux", rubro: "Hogar y oficio", tipo: "Comercios · Ejemplo" },
    { nombre: "Espacio disponible", rubro: "Guía de comercios", tipo: "Comercios" },
    { nombre: "Dental Ar Sourdeaux", rubro: "Profesionales", tipo: "Profesionales · Ejemplo" },
    { nombre: "Espacio disponible", rubro: "Buscador de profesionales", tipo: "Profesionales" },
    { nombre: "Espacio disponible", rubro: "Avisos de vecinos", tipo: "Clasificados" },
    { nombre: "Espacio disponible", rubro: "Agenda del barrio", tipo: "Agenda" },
  ],

  avisos: [
    {
      id: "servi-net",
      slot: "portada",
      slots: ["portada", "clasificados"],
      nombre: "Servi-Net",
      tipo: "Portada 1",
      imagen: "img/avisos/servi-net.png",
      href: "https://servi-net.com.ar/",
      alt: "Servi-Net, tu aliado tecnológico. Tecnología para impulsar y proteger tu empresa. Infraestructura, servidores y nube. Redes, WiFi y monitoreo. Ciberseguridad y protección de datos. Cámaras, alarmas y control de acceso. Desarrollo web, aplicaciones y Google Ads. info@servinet.com.ar. +54 11 4030-6408. servi-net.com.ar",
    },
    {
      id: "portada-farmacia",
      slot: "portada",
      nombre: "Farmacia Álvarez",
      tipo: "Portada 2",
      ejemplo: true,
      texto: "Obras sociales, medicamentos, perfumería y ortopedia. En Rosario desde 1961.",
      dato: "Rosario 4605 · 11 2889-6715",
    },
    {
      id: "portada-libre",
      slot: "portada",
      nombre: "Tu aviso de portada",
      tipo: "Portada 3",
      vacante: true,
      texto: "Tercer lugar de tapa. Sale en el home, en la edición impresa en pantalla y en el envío.",
      cta: "Reservar portada",
    },
    {
      id: "actualidad-veterinario",
      slot: "actualidad",
      nombre: "Hospital Veterinario Adolfo Sourdeaux",
      tipo: "Actualidad",
      ejemplo: true,
      texto: "Clínica, imágenes e internación junto a la estación.",
      dato: "Luis Espinosa 1760 · 11 4748-9159",
    },
    {
      id: "actualidad-libre",
      slot: "actualidad",
      nombre: "Tu aviso en Actualidad",
      tipo: "Actualidad",
      vacante: true,
      texto: "Al lado de las notas del barrio y de Malvinas. Quien abre la sección lo ve primero.",
      cta: "Anunciar en Actualidad",
    },
    {
      id: "comercios-bulonera",
      slot: "comercios",
      nombre: "Ferretería Bulonera Sourdeaux",
      tipo: "Comercios",
      ejemplo: true,
      texto: "Ferretería y bulonería sobre Rosario, con delivery publicado.",
      dato: "Rosario 4635 · Lun a Sáb 8 a 20 · 11 2417-2566",
    },
    {
      id: "comercios-libre",
      slot: "comercios",
      nombre: "Tu aviso en Comercios",
      tipo: "Comercios",
      vacante: true,
      texto: "Espacio en la guía para comprar cerca. Ideal para un local de Rosario, Derqui o Winter.",
      cta: "Anunciar en Comercios",
    },
    {
      id: "profesionales-dental",
      slot: "profesionales",
      nombre: "Dental Ar Sourdeaux",
      tipo: "Profesionales",
      ejemplo: true,
      texto: "Odontología integral: implantes, prótesis, ortodoncia y atención a niños.",
      dato: "Rosario 4680 · 11 6206-3510",
    },
    {
      id: "profesionales-libre",
      slot: "profesionales",
      nombre: "Tu aviso en Profesionales",
      tipo: "Profesionales",
      vacante: true,
      texto: "Consultorio, estudio u oficio. Queda arriba del buscador, no perdido en el listado.",
      cta: "Anunciar en Profesionales",
    },
    {
      id: "clasificados-libre-1",
      slot: "clasificados",
      nombre: "Tu clasificado destacado",
      tipo: "Clasificados",
      vacante: true,
      texto: "Alquiler, venta, empleo o servicio. Un recuadro corto que se reenvía por WhatsApp.",
      cta: "Publicar clasificado",
    },
    {
      id: "clasificados-libre-2",
      slot: "clasificados",
      nombre: "Segundo espacio de clasificados",
      tipo: "Clasificados",
      vacante: true,
      texto: "Otro lugar fijo en la sección, para no competir solo con el listado de vecinos.",
      cta: "Reservar este espacio",
    },
    {
      id: "agenda-libre",
      slot: "eventos",
      nombre: "Tu aviso en la Agenda",
      tipo: "Agenda",
      vacante: true,
      texto: "Al lado de ferias, clubes y escuelas. Sirve para un sponsor de evento o un salón.",
      cta: "Anunciar en Agenda",
    },
  ],
};
