window.REVISTA_DATA = {
  edicion: {
    numero: 1,
    mes: "Septiembre",
    anio: 2026,
    titulo: "Primavera en el Km 30",
    bajada:
      "La primera edición digital de Adolfo Sourdeaux: el corredor de la estación, comercios de Rosario y Derqui, profesionales del barrio y la agenda que se comparte de vecino a vecino.",
    fecha: "11 de septiembre de 2026",
    portadaTema: "primavera",
  },

  nav: [
    { href: "index.html", label: "Inicio", page: "home" },
    { href: "edicion.html", label: "Edición", page: "edicion" },
    { href: "actualidad.html", label: "Actualidad", page: "actualidad" },
    { href: "comercios.html", label: "Comercios", page: "comercios" },
    { href: "profesionales.html", label: "Profesionales", page: "profesionales" },
    { href: "clasificados.html", label: "Clasificados", page: "clasificados" },
    { href: "eventos.html", label: "Agenda", page: "eventos" },
    { href: "anunciantes.html", label: "Anunciantes", page: "anunciantes" },
    { href: "recibir.html", label: "Recibir", page: "recibir" },
    { href: "difundir.html", label: "Difundir", page: "difundir" },
  ],

  secciones: [
    {
      id: "actualidad",
      nombre: "Actualidad",
      desc: "Lo que pasa en Sourdeaux y Malvinas Argentinas.",
      href: "actualidad.html",
    },
    {
      id: "barrio",
      nombre: "Barrio",
      desc: "Historias, vecinos y memoria del Km 30.",
      href: "actualidad.html#barrio",
    },
    {
      id: "comercios",
      nombre: "Comercios",
      desc: "Guía de negocios para comprar cerca.",
      href: "comercios.html",
    },
    {
      id: "profesionales",
      nombre: "Profesionales",
      desc: "Médicos, oficios y estudios del barrio.",
      href: "profesionales.html",
    },
    {
      id: "clasificados",
      nombre: "Clasificados",
      desc: "Avisos de vecinos, alquileres y servicios.",
      href: "clasificados.html",
    },
    {
      id: "eventos",
      nombre: "Agenda",
      desc: "Ferias, clubes, escuelas y cultura.",
      href: "eventos.html",
    },
  ],

  articulos: [
    {
      id: "corredor-estacion-primavera",
      seccion: "actualidad",
      kicker: "Portada · Edición 01",
      titulo: "Sourdeaux se pone en marcha: el corredor de la estación",
      bajada:
        "Rosario, Gilardi, Juan Madera y Juárez Celman recuperan vereda, luz y movimiento. Con la primavera, el casco del Km 30 vuelve a ser el lugar donde el barrio compra en el barrio.",
      cuerpo: [
        "Septiembre llega a Ingeniero Adolfo Sourdeaux con otra luz. Quienes bajan del Belgrano Norte en Rosario y Madera lo ven de inmediato: el andén ya no es solo un paso. Alrededor de la estación se arma un corredor peatonal y comercial —veredas nuevas, iluminación, bancos— que une Juárez Celman, Gilardi y Juan Madera con el pulso de siempre de Derqui y Rosario.",
        "En esta primera edición de Revista Adolfo Sourdeaux nos propusimos algo simple: que un vecino pueda encontrar un plomero, un almacén, un pediatra o un aviso clasificado sin salir del WhatsApp ni del mail. Que el comercio de la esquina tenga el mismo lugar que un anuncio grande. Que el profesional del barrio no quede escondido detrás de un directorio de Capital o de Los Polvorines.",
        "El mapa es el de siempre —Malvinas Argentinas, entre Don Torcuato y Villa de Mayo, a un rato de la General Paz— pero la forma de circular la información cambió. Hablamos con comerciantes de Rosario y Derqui, con oficios que recorren todo el Km 30 y con vecinos que organizan la feria, el club y la escuela.",
        "Esta revista se publica en la web y se reparte como se reparte todo acá: un enlace por WhatsApp, un reenvío por mail, una historia en Instagram, una impresión para el mostrador. Si tenés un comercio, un estudio o un oficio, esta edición es también una invitación a ocupar tu lugar.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      portada: true,
      tiempo: "6 min",
    },
    {
      id: "estacion-km30",
      seccion: "barrio",
      kicker: "Barrio",
      titulo: "De Km 30 a Sourdeaux: la estación como plaza",
      bajada:
        "Farmacia, panadería, kiosco, carnicería y el colectivo 341. Un recorrido útil para quien baja del Belgrano Norte y para quien vive a dos cuadras de Rosario.",
      cuerpo: [
        "Muchos vecinos siguen diciendo Km 30. El nombre oficial —Ingeniero Adolfo Sourdeaux— llegó en 1974, pero el andén sigue siendo el mismo punto: el cruce de quienes van a Retiro, de quienes vuelven del laburo y de quienes hacen el recado de la tarde.",
        "En un radio corto conviven oficios, comercios de cercanía y la Unidad Sanitaria. Esa densidad es la que queremos ordenar en la revista: no para inventar un centro comercial, sino para que se vea lo que ya existe entre Rosario, Derqui, Húsares y Coronel Winter.",
        "Si llegás en tren un sábado, la recomendación de esta edición es simple: caminá el corredor, mirá vidrieras y preguntá. El dato que no está en Google Maps suele estar en el mostrador de al lado.",
      ],
      autor: "Lucía Pereyra",
      destacado: true,
      tiempo: "4 min",
    },
    {
      id: "comercios-rosario-derqui",
      seccion: "comercios",
      kicker: "Comercios",
      titulo: "Rosario y Derqui en siete paradas: de la ferretería a la mesa",
      bajada:
        "Una guía rápida de comercios que el barrio usa todas las semanas, con WhatsApp y horario para no ir al pedo.",
      cuerpo: [
        "Rosario y Santiago Derqui son las costillas comerciales de Sourdeaux. No hace falta una encuesta: cualquier vecino puede armar de memoria el recorrido del sábado —panadería, carnicería, farmacia, ferretería, el lugar de las facturas.",
        "En esta edición destacamos comercios que ya están en nuestra guía y que aceptan consulta por WhatsApp. La idea no es reemplazar la vuelta a pie, sino acortar el tiempo entre “necesito esto” y “ya lo tengo”.",
        "Si tu negocio está sobre Rosario, Derqui, Juan Madera o cerca de la estación y todavía no figura, el espacio está abierto: la ficha se carga una vez y viaja en cada edición.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      tiempo: "5 min",
    },
    {
      id: "profesionales-septiembre",
      seccion: "profesionales",
      kicker: "Profesionales",
      titulo: "A quién llamar en septiembre: la guía corta del Km 30",
      bajada:
        "Pediatra, contador, electricista y arquitecto. Cuatro oficios que el barrio busca apenas empieza el mes.",
      cuerpo: [
        "El buscador de profesionales de la revista no es un listado infinito. Es una selección de personas que atienden en Adolfo Sourdeaux, Villa de Mayo y alrededores, con especialidad, zona y WhatsApp a la vista.",
        "En septiembre se repiten cuatro búsquedas: el control de los chicos antes de las actividades, el cierre contable del trimestre, una instalación eléctrica que el invierno dejó floja y un presupuesto de obra chica.",
        "Si sos profesional y trabajás en el barrio, tu ficha puede destacarse en la edición y en el envío que se comparte por mail y WhatsApp. El criterio es claro: que un vecino te encuentre en menos de un minuto.",
      ],
      autor: "Martín Aguirre",
      destacado: false,
      tiempo: "3 min",
    },
    {
      id: "feria-corredor",
      seccion: "eventos",
      kicker: "Agenda",
      titulo: "La feria de primavera se planta en el corredor de la estación",
      bajada:
        "Emprendimientos de Malvinas, huerta, indumentaria y una mesa para que los chicos se queden un rato más.",
      cuerpo: [
        "La agenda de septiembre tiene un ancla: la feria de primavera sobre el corredor peatonal. Es el tipo de evento que el barrio espera porque mezcla lo comercial con lo social. Se va a comprar y se termina charlando.",
        "Esta edición anticipa horarios, rubros y cómo llegar —a pie desde el andén, o en el 341. También dejamos un espacio para que los expositores figuren con nombre y contacto, igual que un comercio de calle.",
        "Si organizás un evento en un club, una escuela o una plaza, mandalo: la agenda se actualiza en la web y viaja en el envío semanal.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      tiempo: "3 min",
    },
    {
      id: "publicar-aviso",
      seccion: "actualidad",
      kicker: "Oficina",
      titulo: "Cómo anunciar en la revista: un aviso que se reenvía",
      bajada:
        "La diferencia de un anuncio digital de barrio es que no se queda en una web: se manda por WhatsApp, por mail y queda en el mostrador.",
      cuerpo: [
        "Revista Adolfo Sourdeaux se diseña para dos pantallas: la del celular de un vecino y la del monitor de quien la abre desde el hosting. Por eso cada aviso tiene un enlace corto, un botón de WhatsApp y una versión que se puede reenviar.",
        "Los paquetes van desde el clasificado de 40 palabras hasta la ficha destacada de comercio o profesional, el banner de portada y la mención en el envío de la edición.",
        "No hace falta una agencia. Hace falta un logo, tres renglones y un teléfono. El resto lo armamos nosotros para que se vea como revista, no como un post suelto.",
      ],
      autor: "Comercial SOURDEAUX",
      destacado: false,
      tiempo: "4 min",
    },
  ],

  comercios: [
    {
      id: "panaderia-anden",
      nombre: "Panadería El Andén",
      rubro: "Gastronomía",
      dest: true,
      dir: "Rosario 2180, Adolfo Sourdeaux",
      horario: "Lun a Dom 6 a 13 y 16 a 21",
      tel: "11 4666-1101",
      wa: "5491146661101",
      desc: "Facturas al horno, pan de campo y el café de la mañana junto a la estación.",
    },
    {
      id: "ferreteria-winter",
      nombre: "Ferretería Don Winter",
      rubro: "Hogar y oficio",
      dest: true,
      dir: "Coronel Winter 890, Adolfo Sourdeaux",
      horario: "Lun a Vie 8:30 a 18 · Sáb 8:30 a 13",
      tel: "11 4666-2202",
      wa: "5491146662202",
      desc: "Bulonería, herramientas y corte. Presupuesto por WhatsApp para el arreglo de la casa.",
    },
    {
      id: "farmacia-derqui",
      nombre: "Farmacia Derqui",
      rubro: "Salud",
      dest: true,
      dir: "Santiago Derqui 1240, Adolfo Sourdeaux",
      horario: "Lun a Sáb 8 a 22 · Dom 9 a 14",
      tel: "11 4666-3303",
      wa: "5491146663303",
      desc: "Obra social, dermocosmética y delivery al Km 30 en el día.",
    },
    {
      id: "dietetica-km30",
      nombre: "Dietética Km 30",
      rubro: "Almacén",
      dest: false,
      dir: "Gilardi 560, Adolfo Sourdeaux",
      horario: "Lun a Sáb 9 a 13 y 16 a 20",
      tel: "11 4666-4404",
      wa: "5491146664404",
      desc: "Granel, sin TACC y productos para la semana sin ir al súper grande.",
    },
    {
      id: "taller-madera",
      nombre: "Taller Mecánica Madera",
      rubro: "Automotriz",
      dest: false,
      dir: "Juan Madera 980, Adolfo Sourdeaux",
      horario: "Lun a Vie 8 a 18 · Sáb 8 a 13",
      tel: "11 4666-5505",
      wa: "5491146665505",
      desc: "Service, frenos y diagnóstico. Turno por WhatsApp para no dejar el auto a ciegas.",
    },
    {
      id: "salon-husares",
      nombre: "Salón Húsares",
      rubro: "Belleza",
      dest: false,
      dir: "Húsares 430, Adolfo Sourdeaux",
      horario: "Mar a Sáb 9 a 19",
      tel: "11 4666-6606",
      wa: "5491146666606",
      desc: "Peluquería, color y uñas. Agenda de septiembre con horarios de tarde.",
    },
    {
      id: "libreria-andes",
      nombre: "Librería Los Andes",
      rubro: "Educación",
      dest: false,
      dir: "Juárez Celman 710, Adolfo Sourdeaux",
      horario: "Lun a Vie 9 a 13 y 15 a 19",
      tel: "11 4666-7707",
      wa: "5491146667707",
      desc: "Útiles, fotocopias y listas de colegios del barrio y de Villa de Mayo.",
    },
    {
      id: "veterinaria-corredor",
      nombre: "Veterinaria El Corredor",
      rubro: "Mascotas",
      dest: true,
      dir: "Rosario 1950, Adolfo Sourdeaux",
      horario: "Lun a Sáb 9:30 a 19",
      tel: "11 4666-8808",
      wa: "5491146668808",
      desc: "Clínica, vacunas y alimento. Guardia coordinada por teléfono.",
    },
  ],

  profesionales: [
    {
      id: "dra-benitez",
      nombre: "Dra. Carolina Benítez",
      oficio: "Pediatría",
      rubro: "Salud",
      busca: "médico medica pediatra doctor chicos",
      dest: true,
      zona: "Cerca de estación",
      dir: "Consultorio en Santiago Derqui, Adolfo Sourdeaux",
      mat: "MN 128.440",
      wa: "5491150020001",
      desc: "Controles, vacunas y seguimiento escolar. Turnos por la tarde.",
    },
    {
      id: "estudio-roldan",
      nombre: "Estudio Roldán",
      oficio: "Contador público",
      rubro: "Estudios",
      dest: true,
      zona: "Rosario",
      dir: "Rosario 2010, Adolfo Sourdeaux",
      mat: "CPCECABA T° 312",
      wa: "5491150020002",
      desc: "Monotributo, sociedades y liquidaciones para comercios del Km 30.",
    },
    {
      id: "arq-molina",
      nombre: "Arq. Diego Molina",
      oficio: "Arquitectura y obra",
      rubro: "Oficios",
      dest: true,
      zona: "Sourdeaux y Villa de Mayo",
      dir: "Atención en Malvinas Argentinas",
      mat: "CAPBA 1",
      wa: "5491150020003",
      desc: "Refacciones, planos y dirección de obra chica y mediana.",
    },
    {
      id: "elec-perez",
      nombre: "Javier Pérez",
      oficio: "Electricista matriculado",
      rubro: "Oficios",
      busca: "luz tablero cortocircuito urgente",
      dest: false,
      zona: "Todo Sourdeaux",
      dir: "Domicilio y comercios",
      mat: "Mat. CABA/PBA",
      wa: "5491150020004",
      desc: "Tableros, cortocircuitos y certificación. Urgencias del día.",
    },
    {
      id: "abog-silva",
      nombre: "Dra. Elena Silva",
      oficio: "Abogada · Familia y laboral",
      rubro: "Estudios",
      dest: false,
      zona: "Malvinas y Zona Norte",
      dir: "Estudio en Adolfo Sourdeaux",
      mat: "T° XII F° 88",
      wa: "5491150020005",
      desc: "Consultas por videollamada o en el estudio. Primera reunión sin cargo.",
    },
    {
      id: "psi-gomez",
      nombre: "Lic. Andrés Gómez",
      oficio: "Psicología",
      rubro: "Salud",
      dest: false,
      zona: "Adolfo Sourdeaux",
      dir: "Consultorio a 4 cuadras de la estación",
      mat: "MN 67.210",
      wa: "5491150020006",
      desc: "Adultos y adolescentes. Obras sociales y particular.",
    },
    {
      id: "plom-ruiz",
      nombre: "Héctor Ruiz",
      oficio: "Plomería y gas",
      rubro: "Oficios",
      dest: true,
      busca: "plomero plomera gasista caños termotanque",
      zona: "Sourdeaux y Villa de Mayo",
      dir: "Servicio a domicilio",
      mat: "Gasista 2da categoría",
      wa: "5491150020007",
      desc: "Pérdidas, termotanque y cañerías. Presupuesto el mismo día.",
    },
    {
      id: "prof-alvarez",
      nombre: "Prof. Marina Álvarez",
      oficio: "Clases de inglés",
      rubro: "Educación",
      dest: false,
      zona: "Adolfo Sourdeaux",
      dir: "Domicilio o virtual",
      mat: "Prof. UNLP",
      wa: "5491150020008",
      desc: "Niños y adultos. Grupos chicos para el ciclo de octubre.",
    },
  ],

  clasificados: [
    {
      id: "c1",
      tipo: "Alquiler",
      titulo: "Departamento 2 ambientes cerca de la estación",
      texto:
        "Luminoso, planta baja, patio chico. Ideal pareja. Expensas bajas. Entrada inmediata.",
      contacto: "11 5002-2010",
      dest: true,
    },
    {
      id: "c2",
      tipo: "Venta",
      titulo: "Ford Ka 2018, único dueño",
      texto: "110.000 km, service al día, listo para transferir. Se entrega en Adolfo Sourdeaux.",
      contacto: "11 5002-2011",
      dest: false,
    },
    {
      id: "c3",
      tipo: "Servicio",
      titulo: "Jardinería y corte de césped por manzana",
      texto: "Mantenimiento mensual de fondos y frentes. Presupuesto sin cargo.",
      contacto: "11 5002-2012",
      dest: false,
    },
    {
      id: "c4",
      tipo: "Busco",
      titulo: "Niñera para dos chicos, tardes de lunes a jueves",
      texto: "Zona estación. Referencias excluyentes. Empezamos en octubre.",
      contacto: "11 5002-2013",
      dest: false,
    },
    {
      id: "c5",
      tipo: "Empleo",
      titulo: "Mozo/a para confitería de Rosario",
      texto: "Turno tarde, experiencia en mostrador. Entrevista esta semana.",
      contacto: "11 5002-2014",
      dest: true,
    },
    {
      id: "c6",
      tipo: "Servicio",
      titulo: "Costura y arreglos de indumentaria",
      texto: "Dobladillos, cierres y uniformes escolares. Retiro en el barrio.",
      contacto: "11 5002-2015",
      dest: false,
    },
  ],

  eventos: [
    {
      id: "e1",
      fecha: "Sáb 13 sep",
      hora: "10 a 18",
      titulo: "Feria de primavera",
      lugar: "Corredor peatonal de la estación",
      desc: "Productores, indumentaria, huerta y patio de comidas del barrio.",
    },
    {
      id: "e2",
      fecha: "Dom 14 sep",
      hora: "9:30",
      titulo: "Entrenamiento abierto del club",
      lugar: "Club de barrio",
      desc: "Inferiores y una prueba para quienes quieren sumarse al fútbol de 7.",
    },
    {
      id: "e3",
      fecha: "Jue 18 sep",
      hora: "19:00",
      titulo: "Charla de monotributo para comercios",
      lugar: "Salón de Estudio Roldán",
      desc: "Cupos limitados. Inscripción por WhatsApp de la revista.",
    },
    {
      id: "e4",
      fecha: "Sáb 20 sep",
      hora: "16:00",
      titulo: "Cuentos en la librería",
      lugar: "Librería Los Andes",
      desc: "Lectura para chicos de 4 a 8. Sin inscripción.",
    },
    {
      id: "e5",
      fecha: "Vie 26 sep",
      hora: "21:00",
      titulo: "Noche de peña",
      lugar: "Salón de eventos de Malvinas",
      desc: "Música en vivo y mesa de empanadas. Entrada anticipada.",
    },
  ],

  paquetes: [
    {
      id: "clasificado",
      nombre: "Clasificado",
      precio: "Consultar",
      detalle: "40 palabras + teléfono. Sale en la web y en el envío de la edición.",
      items: ["Texto breve", "Una categoría", "Link de WhatsApp", "Vigencia 15 días"],
    },
    {
      id: "ficha",
      nombre: "Ficha comercio o profesional",
      precio: "Consultar",
      detalle: "Tu tarjeta permanente en el buscador, con foto de rubro y contacto.",
      items: ["Nombre y rubro", "Dirección y horario", "Botón de WhatsApp", "Aparece en búsquedas"],
    },
    {
      id: "destacado",
      nombre: "Destacado de edición",
      precio: "Consultar",
      detalle: "Lugar fijo en portada o en la página de la sección durante un mes.",
      items: ["Recuadro editorial", "Mención en el mail", "Prioridad en el listado", "Diseño incluido"],
    },
    {
      id: "portada",
      nombre: "Banner de portada",
      precio: "Consultar",
      detalle: "La primera impresión de quien abre la revista o el enlace compartido.",
      items: ["Home + edición", "Formato revista", "Envío WhatsApp", "Reporte de clics"],
    },
  ],

  anunciantes: [
    { nombre: "Ferretería Don Winter", rubro: "Hogar y oficio", tipo: "Destacado" },
    { nombre: "Farmacia Derqui", rubro: "Salud", tipo: "Portada" },
    { nombre: "Estudio Roldán", rubro: "Profesionales", tipo: "Ficha" },
    { nombre: "Veterinaria El Corredor", rubro: "Mascotas", tipo: "Destacado" },
  ],
};
