window.REVISTA_DATA = {
  edicion: {
    numero: 1,
    mes: "Septiembre",
    anio: 2026,
    titulo: "Libros, paseo y el Km 30",
    bajada:
      "La 7ª Feria del Libro de Malvinas, el Paseo Ferial junto a la estación y una guía de comercios reales de Rosario y Derqui.",
    fecha: "11 de septiembre de 2026",
    portadaTema: "primavera",
  },

  nav: [
    { href: "index.html", label: "Inicio", page: "home" },
    { href: "edicion.html", label: "Edición", page: "edicion" },
    { href: "actualidad.html", label: "Actualidad", page: "actualidad" },
    { href: "indice.html", label: "Índice", page: "indice" },
    { href: "comercios.html", label: "Comercios", page: "comercios" },
    { href: "profesionales.html", label: "Profesionales", page: "profesionales" },
    { href: "clasificados.html", label: "Clasificados", page: "clasificados" },
    { href: "eventos.html", label: "Agenda", page: "eventos" },
    { href: "anunciantes.html", label: "Anunciantes", page: "anunciantes" },
    { href: "recibir.html", label: "Recibir", page: "recibir" },
    { href: "difundir.html", label: "Difundir", page: "difundir" },
  ],

  secciones: [
    {
      id: "actualidad",
      nombre: "Actualidad",
      desc: "Lo que pasa en Sourdeaux y Malvinas Argentinas.",
      href: "actualidad.html",
    },
    {
      id: "barrio",
      nombre: "Barrio",
      desc: "Historias, vecinos y memoria del Km 30.",
      href: "actualidad.html#barrio",
    },
    {
      id: "indice",
      nombre: "Índice Km 30",
      desc: "De la A a la Z, con teléfono a la vista.",
      href: "indice.html",
    },
    {
      id: "comercios",
      nombre: "Comercios",
      desc: "Guía de negocios para comprar cerca.",
      href: "comercios.html",
    },
    {
      id: "profesionales",
      nombre: "Profesionales",
      desc: "Salud, oficios y estudios del barrio.",
      href: "profesionales.html",
    },
    {
      id: "clasificados",
      nombre: "Clasificados",
      desc: "Avisos, profesionales y clasificados de vecinos.",
      href: "clasificados.html",
    },
    {
      id: "eventos",
      nombre: "Agenda",
      desc: "Ferias, clubes, escuelas y cultura.",
      href: "eventos.html",
    },
  ],

  articulos: [
    {
      id: "feria-libro-malvinas-2026",
      seccion: "actualidad",
      kicker: "Portada · Edición 01",
      titulo: "Esta semana: la 7ª Feria del Libro de Malvinas Argentinas",
      bajada:
        "Del 11 al 20 de septiembre, junto al Palacio Municipal. Entrada libre. Desde Sourdeaux se llega por el Belgrano Norte y el 341.",
      cuerpo: [
        "Malvinas Argentinas abre su 7ª Feria del Libro entre el 11 y el 20 de septiembre, en las inmediaciones del Palacio Municipal, Av. Presidente Perón 4276. Lo organiza el Municipio con la Fundación El Libro. La entrada es libre y gratuita.",
        "Los horarios publicados por el municipio son de lunes a viernes de 9 a 20, y sábados, domingos y feriados de 12 a 21. Contarte Cultura anticipó más de 60 stands y una programación con autores como Darío Sztajnszrajber, Pedro Saborido, Florencia Canale y Reynaldo Sietecase. Los chicos que vayan con la escuela reciben un chequelibro para comprar en el predio.",
        "Para un vecino de Adolfo Sourdeaux el trayecto es corto: el Belgrano Norte deja en la estación del Km 30 y de ahí se conecta hacia Los Polvorines y el centro municipal. El 341 también recorre el partido.",
        "Esta edición de la revista sale el mismo día de la apertura. Si vas, llevá DNI, anotá los stands que te sirvan y, si tenés un comercio o un oficio en Rosario o Derqui, esta semana es buena para que el barrio te encuentre.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      portada: true,
      tiempo: "5 min",
    },
    {
      id: "paseo-ferial-estacion",
      seccion: "barrio",
      kicker: "Barrio",
      titulo: "El Paseo Ferial ya es la plaza de la estación",
      bajada:
        "Entre Derqui y Juan Madera hay 24 puestos, anfiteatro y luz LED. Funciona todos los días de 8 a 20, con rotación de emprendedores.",
      cuerpo: [
        "En octubre de 2025 el municipio inauguró el Paseo Ferial de Ing. Adolfo Sourdeaux. El recinto suma unos 400 metros cuadrados junto a la estación del Belgrano Norte, de Derqui a Juan Madera. Hay 24 puestos, sectores de descanso y un anfiteatro.",
        "El intendente Leonardo Nardini dijo entonces que el lugar no era solo un paseo iluminado: también daba salida laboral a casi 50 feriantes que rotan los puestos. Gabriela y Priscila, de Esencia Dulce, contaron que se anotaron por la convocatoria del CAM después de vender por WhatsApp. María Crochet, de Grand Bourg, lleva tejidos y clases.",
        "Antes, el municipio ya había pavimentado y peatonalizado Juárez Celman, Juan Madera y Gilardi, y había renovado la estación (andenes, LED, accesos y cámaras). El nombre oficial del barrio es Ingeniero Adolfo Sourdeaux; muchos vecinos siguen diciendo Km 30.",
        "Hoy el paseo abre todos los días de 8 a 20. Si organizás un evento o tenés un puesto, mandalo a la revista: la agenda se actualiza en la web.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      tiempo: "5 min",
    },
    {
      id: "guia-rosario-derqui",
      seccion: "comercios",
      kicker: "Comercios",
      titulo: "Rosario y Derqui, comercio por comercio",
      bajada:
        "Farmacia Álvarez, ferreterías de la estación, panadería del Km 30 y el hospital veterinario de Luis Espinosa. Datos tomados de sitios y guías públicas.",
      cuerpo: [
        "La costilla comercial de Sourdeaux sigue siendo Rosario, entre la estación y Derqui. En esta guía no inventamos fichas: cargamos comercios que figuran con dirección y, cuando existe, teléfono publicado.",
        "Farmacia Álvarez está en Rosario 4605 desde hace décadas. Su sitio propio publica obras sociales, dos líneas fijas (4748-1868 y 4748-0415) y WhatsApp 11 2889-6715. A pocos metros aparecen Ferretería Nasi (Rosario 4591) y Ferretería Bulonera Sourdeaux (Rosario 4635), esta última con horario extendido y delivery.",
        "Sobre Derqui, la Panadería La Nueva Km30 (Derqui 1331) abre de madrugada y Electricidad López (Derqui 1015) cubre materiales eléctricos. En Luis Espinosa 1760 funciona el Hospital Veterinario Adolfo Sourdeaux, con atención de semana y guardia de fin de semana.",
        "Si tu local está y no figura, o si un dato cambió, escribinos. La ficha se corrige una vez y viaja en cada edición.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      tiempo: "4 min",
    },
    {
      id: "salud-km30",
      seccion: "profesionales",
      kicker: "Profesionales",
      titulo: "Dónde atenderse en el Km 30: sanitaria, odontólogos y oficios",
      bajada:
        "La Unidad Sanitaria Km 30 está en Rosario. En la misma calle hay consultorios odontológicos. El buscador solo lista fichas con domicilio publicado.",
      cuerpo: [
        "La atención pública del barrio pasa por la Unidad Sanitaria Km 30 / Unidad Funcional Km 30, en Rosario 4472/4572, entre Portela y Rondeau. Es un centro municipal con atención diaria y especialidades. El municipio también readecuó el Centro de Salud ARA San Juan, en Rosario al 4400.",
        "En oficios del barrio está Servi-Net: redes, WiFi, fibra, servidores, cámaras y soporte de PC, con WhatsApp 11 4030-6408. En el casco también hay consultorios odontológicos con domicilio visible: Dental Ar Sourdeaux, Rosario 4680, y el Centro Odontológico Adriana Roel, Av. San Martín 319.",
        "Si atendés en Sourdeaux, Villa de Mayo o Los Polvorines, mandá tu ficha: nombre, matrícula, zona y WhatsApp.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: false,
      tiempo: "3 min",
    },
    {
      id: "agenda-septiembre",
      seccion: "eventos",
      kicker: "Agenda",
      titulo: "Qué hay para hacer: feria del libro, paseo y mercado itinerante",
      bajada:
        "Tres citas reales del distrito. El Paseo Ferial es todos los días; la Feria del Libro, esta quincena; Mercado Malvinas rota por las plazas.",
      cuerpo: [
        "La cita grande de septiembre es la Feria del Libro, del 11 al 20, junto al Palacio Municipal. El Paseo Ferial de Sourdeaux, en cambio, no es un evento de un día: abre de 8 a 20 junto a la estación, con puestos rotativos.",
        "Mercado Malvinas es una feria municipal de alimentos (almacén, lácteos, verdura y avícola) que se planta en Plaza Güemes, General Pico y Pío XII. En las últimas visitas publicadas funcionó de 9 a 14, con hasta 40% de descuento presentando DNI, y se suspende por lluvia. Las fechas cambian cada semana: hay que mirar el anuncio municipal.",
        "Si un club, una escuela o un salón tiene una fecha cerrada, mandala. No publicamos horarios inventados.",
      ],
      autor: "Redacción SOURDEAUX",
      destacado: true,
      tiempo: "3 min",
    },
    {
      id: "publicar-aviso",
      seccion: "actualidad",
      kicker: "Oficina",
      titulo: "Cómo entrar al índice del Km 30",
      bajada:
        "Clasificado, ficha en el padrón y un módulo en la grilla. El aviso se lee en el celular y se reenvía.",
      cuerpo: [
        "En Sourdeaux el recado sigue siendo el mismo: un teléfono en la vidriera, un nombre en el mostrador y un mensaje al grupo de la manzana. El índice del Km 30 ordena eso, de la A a la Z.",
        "El clasificado es corto y tiene categoría: se busca, se alquila, se vende, empleo o servicio. La ficha entra al buscador y al índice. El módulo —simple, doble o banner— ocupa un lugar fijo en la grilla de Clasificados y Anunciantes.",
        "Para sumarte hace falta nombre, rubro, dirección y un WhatsApp. No inventamos fichas: si el dato no está publicado, no entra.",
      ],
      autor: "Comercial SOURDEAUX",
      destacado: false,
      tiempo: "3 min",
    },
  ],

  comercios: [
    {
      id: "servi-net-comercio",
      nombre: "Servi-Net",
      rubro: "Informática",
      dest: true,
      dir: "Adolfo Sourdeaux, Malvinas Argentinas",
      horario: "A domicilio y por WhatsApp",
      tel: "11 4030-6408",
      wa: "5491140306408",
      desc: "Redes, WiFi, fibra, servidores, cámaras y soporte de PC para casas y comercios del Km 30.",
    },
    {
      id: "farmacia-alvarez",
      nombre: "Farmacia Álvarez",
      rubro: "Salud",
      dest: true,
      dir: "Rosario 4605, Ing. Adolfo Sourdeaux",
      horario: "Consultá turno y horario en el local o por WhatsApp",
      tel: "11 4748-1868",
      wa: "5491128896715",
      desc: "Desde 1961. Obras sociales, medicamentos, perfumería y ortopedia. También 11 4748-0415.",
    },
    {
      id: "ferreteria-bulonera",
      nombre: "Ferretería Bulonera Sourdeaux",
      rubro: "Hogar y oficio",
      dest: true,
      dir: "Rosario 4635, Ing. Adolfo Sourdeaux",
      horario: "Lun a Sáb 8 a 20 · Dom 8 a 13",
      tel: "11 2417-2566",
      desc: "Ferretería y bulonería sobre Rosario. Delivery publicado. Conviene llamar antes si buscás un bulón puntual.",
    },
    {
      id: "ferreteria-nasi",
      nombre: "Ferretería Nasi",
      rubro: "Hogar y oficio",
      dest: false,
      dir: "Rosario 4591, Ing. Adolfo Sourdeaux",
      horario: "Lun a Vie 8:30 a 13 y 16 a 19 · Sáb 8:30 a 13",
      tel: "11 4748-9771",
      desc: "Herramientas y ferretería a metros de la estación, a nombre de Leonardo Santiago Nasi.",
    },
    {
      id: "electricidad-lopez",
      nombre: "Electricidad López",
      rubro: "Hogar y oficio",
      dest: true,
      dir: "Derqui 1015, Ing. Adolfo Sourdeaux",
      horario: "Lun a Vie 8:30 a 13 y 14:30 a 18:30 · Sáb 8:30 a 13",
      tel: "11 4741-4757",
      desc: "Materiales eléctricos sobre Derqui, a pocas cuadras de la estación.",
    },
    {
      id: "panaderia-km30",
      nombre: "Panadería La Nueva Km30",
      rubro: "Gastronomía",
      dest: true,
      dir: "Derqui 1331, Ing. Adolfo Sourdeaux",
      horario: "Lun a Sáb 6:30 a 20:30 · Dom 9:15 a 13 y 16:30 a 19",
      desc: "Panadería del casco, sobre Derqui. No hay teléfono público; se compra en el mostrador.",
    },
    {
      id: "pan-del-cielo",
      nombre: "Pan Del Cielo",
      rubro: "Gastronomía",
      dest: false,
      dir: "Rosario 4586, Ing. Adolfo Sourdeaux",
      horario: "Consultá horario en el local",
      desc: "Panadería sobre Rosario, frente al movimiento de la estación.",
    },
    {
      id: "hospital-veterinario",
      nombre: "Hospital Veterinario Adolfo Sourdeaux",
      rubro: "Mascotas",
      dest: true,
      dir: "Luis Espinosa 1760, Ing. Adolfo Sourdeaux",
      horario: "Lun a Vie 9 a 18 · Sáb y Dom 9 a 13",
      tel: "11 4748-9159",
      desc: "Clínica, imágenes e internación. El teléfono más repetido en las guías es 4748-9159.",
    },
    {
      id: "ferreteria-carti",
      nombre: "Ferretería Carti",
      rubro: "Hogar y oficio",
      dest: false,
      dir: "Luis Espinosa 1561, Ing. Adolfo Sourdeaux",
      horario: "Lun a Vie 8 a 14:30 y 15:30 a 19 · Sáb y Dom 8 a 18",
      tel: "11 4741-7900",
      desc: "Ferretería sobre Luis Espinosa, a la altura del hospital veterinario.",
    },
    {
      id: "sanitarios-lg",
      nombre: "Sanitarios LG",
      rubro: "Hogar y oficio",
      dest: false,
      dir: "Coronel Winter 4386, Ing. Adolfo Sourdeaux",
      horario: "Lun a Vie 8 a 13 y 14 a 18:30 · Sáb 8 a 16",
      tel: "11 4748-6187",
      desc: "Sanitarios y materiales para baño sobre Coronel Winter.",
    },
    {
      id: "ferreteria-la-curva",
      nombre: "Ferretería La Curva",
      rubro: "Hogar y oficio",
      dest: false,
      dir: "Viedma 4373, Ing. Adolfo Sourdeaux",
      horario: "Lun a Sáb 8:30 a 13 y 16:30 a 20 · Dom 9:30 a 13",
      tel: "11 4846-0527",
      desc: "Ferretería de barrio sobre Viedma.",
    },
    {
      id: "carniceria-amistad",
      nombre: "Carnicería La Amistad",
      rubro: "Almacén",
      dest: false,
      dir: "Coronel Winter, Ing. Adolfo Sourdeaux",
      horario: "Consultá horario en el local",
      tel: "11 2446-8211",
      desc: "Carnicería sobre Winter, con entrega en el día según las guías.",
    },
    {
      id: "vaquita-kennedy",
      nombre: "Vaquita",
      rubro: "Almacén",
      dest: false,
      dir: "J. F. Kennedy 4787, Ing. Adolfo Sourdeaux",
      horario: "Consultá horario en el local",
      tel: "11 4748-9803",
      desc: "Carnicería / almacén sobre Kennedy.",
    },
    {
      id: "tintos-peluqueria",
      nombre: "Tinto's Peluquería",
      rubro: "Belleza",
      dest: false,
      dir: "Rosario 4578, Ing. Adolfo Sourdeaux",
      horario: "Consultá horario en el local",
      desc: "Peluquería sobre Rosario, a metros de la estación. Sin teléfono publicado.",
    },
  ],

  profesionales: [
    {
      id: "servi-net",
      nombre: "Servi-Net",
      oficio: "Redes, informática y ciberseguridad",
      rubro: "Oficios",
      busca: "redes wifi camaras computadora informatica tecnico pc servidor ciberseguridad fibra router",
      dest: true,
      zona: "Adolfo Sourdeaux y Zona Norte",
      dir: "Atención a domicilio en el Km 30 y Malvinas Argentinas",
      mat: "servi-net.com.ar",
      tel: "11 4030-6408",
      wa: "5491140306408",
      desc: "Redes cableadas y WiFi, fibra, servidores, cámaras, reparación de PC y soporte para comercios. WhatsApp de la casa.",
    },
    {
      id: "dental-ar",
      nombre: "Dental Ar Sourdeaux",
      oficio: "Odontología integral",
      rubro: "Salud",
      busca: "dentista odontologo implante ortodoncia muelas",
      dest: true,
      zona: "Rosario, cerca de estación",
      dir: "Rosario 4680, Ing. Adolfo Sourdeaux",
      mat: "Consultorio",
      tel: "11 6206-3510",
      desc: "Cirugía, implantes, prótesis, endodoncia, ortodoncia y atención a niños. Lun, mar, jue y vie 10 a 19 · Sáb 10 a 18.",
    },
    {
      id: "adriana-roel",
      nombre: "Centro Odontológico Adriana Roel",
      oficio: "Odontología",
      rubro: "Salud",
      busca: "dentista odontologa",
      dest: true,
      zona: "Av. San Martín",
      dir: "Av. San Martín 319, Ing. Adolfo Sourdeaux",
      mat: "Consultorio",
      tel: "11 4748-4560",
      desc: "Consultorio odontológico con domicilio y teléfono publicados en directorios del barrio.",
    },
    {
      id: "unidad-km30",
      nombre: "Unidad Sanitaria Km 30",
      oficio: "Atención primaria municipal",
      rubro: "Salud",
      busca: "medico medica pediatra centro de salud vacuna",
      dest: true,
      zona: "Rosario",
      dir: "Rosario 4572 (e/ Portela y Rondeau), Ing. Adolfo Sourdeaux",
      mat: "Municipal",
      desc: "Centro de salud público con atención diaria y especialidades. También figura como Unidad Funcional Km 30 (Rosario 4472).",
    },
    {
      id: "centro-ara-san-juan",
      nombre: "Centro de Salud ARA San Juan",
      oficio: "Atención primaria municipal",
      rubro: "Salud",
      busca: "medico centro de salud",
      dest: false,
      zona: "Rosario al 4400",
      dir: "Rosario 4400, Ing. Adolfo Sourdeaux",
      mat: "Municipal",
      desc: "El municipio readecuó el edificio para reforzar la atención primaria. Consultá turnos en el centro.",
    },
  ],

  clasificados: [],

  eventos: [
    {
      id: "e1",
      fecha: "11 al 20 sep",
      hora: "Lun a Vie 9 a 20 · Sáb y Dom 12 a 21",
      titulo: "7ª Feria del Libro de Malvinas Argentinas",
      lugar: "Av. Pte. Perón 4276, Palacio Municipal",
      desc: "Entrada libre. Más de 60 stands, autores y chequelibro para escuelas. Municipio y Fundación El Libro.",
    },
    {
      id: "e2",
      fecha: "Todos los días",
      hora: "8 a 20",
      titulo: "Paseo Ferial de Ing. Adolfo Sourdeaux",
      lugar: "Derqui a Juan Madera, junto a la estación",
      desc: "24 puestos rotativos, anfiteatro y paseo peatonal. Emprendimientos locales.",
    },
    {
      id: "e3",
      fecha: "Itinerante",
      hora: "9 a 14 (se suspende por lluvia)",
      titulo: "Mercado Malvinas",
      lugar: "Cuando está en Sourdeaux: Plaza Güemes (Gral. Pico y Pío XII)",
      desc: "Almacén, lácteos, verdura y avícola. Hasta 40% con DNI. Las fechas las anuncia el municipio cada semana.",
    },
  ],

  paquetes: [
    {
      id: "mini",
      nombre: "Mini / clasificado",
      precio: "Valor 1",
      detalle: "El recuadro más chico, como el clasificado de vidriera. 40 palabras y un teléfono.",
      items: ["1/8 de página", "Se busca / Alquiler / Empleo / Servicio", "15 días", "Sale en el envío"],
    },
    {
      id: "simple",
      nombre: "Módulo 1/4",
      precio: "Valor 2",
      detalle: "Un cuarto de la grilla. Nombre, rubro y dato de contacto.",
      items: ["1 columna", "Diseño incluido", "Un mes", "Clasificados o Anunciantes"],
    },
    {
      id: "alto",
      nombre: "Módulo alto",
      precio: "Valor 3",
      detalle: "La misma columna, el doble de alto. Sirve para listar servicios o una matrícula.",
      items: ["1 columna × 2 filas", "Más texto", "Un mes", "Página de profesionales"],
    },
    {
      id: "doble",
      nombre: "Media página",
      precio: "Valor 4",
      detalle: "Dos columnas. Foto chica, horario y WhatsApp.",
      items: ["2 columnas", "Más llegada", "Un mes", "Mención en el mail"],
    },
    {
      id: "cuadrado",
      nombre: "Módulo 1/2 alto",
      precio: "Valor 5",
      detalle: "Medio ancho y dos filas, como el aviso gráfico de Servi-Net.",
      items: ["2 × 2", "Arte propio", "Home + grilla", "Reporte de clics"],
    },
    {
      id: "banner",
      nombre: "Banner de página",
      precio: "Valor 6",
      detalle: "La fila completa. El espacio más visible de la grilla y de la portada.",
      items: ["4 columnas", "Bajo el menú", "Envío WhatsApp", "El de más valor"],
    },
  ],

  anunciantes: [
    { nombre: "Servi-Net", rubro: "Informática y redes", tipo: "1/2 alto · Valor 5", seccion: "Profesionales", tel: "11 4030-6408" },
    { nombre: "Farmacia Álvarez", rubro: "Salud", tipo: "Media página · Valor 4", seccion: "Comercios", tel: "11 4748-1868" },
    { nombre: "Ferretería Bulonera Sourdeaux", rubro: "Hogar y oficio", tipo: "Módulo 1/4 · Valor 2", seccion: "Comercios", tel: "11 2417-2566" },
    { nombre: "Hospital Veterinario Adolfo Sourdeaux", rubro: "Mascotas", tipo: "Media página · Valor 4", seccion: "Comercios", tel: "11 4748-9159" },
    { nombre: "Dental Ar Sourdeaux", rubro: "Salud", tipo: "Módulo 1/4 · Valor 2", seccion: "Profesionales", tel: "11 6206-3510" },
  ],

  avisos: [
    {
      id: "servi-net",
      slot: "portada",
      slots: ["portada", "clasificados"],
      mosaico: ["clasificados", "anunciantes"],
      tamano: "cuadrado",
      fijo: true,
      precio: "Valor 5",
      nombre: "Servi-Net",
      tipo: "1/2 alto",
      imagen: "img/avisos/servi-net.png",
      href: "https://servi-net.com.ar/",
      alt: "Servi-Net, tu aliado tecnológico. Tecnología para impulsar y proteger tu empresa. 11 4030-6408. servi-net.com.ar",
    },
    {
      id: "estudio-km30",
      slot: "profesionales",
      mosaico: ["clasificados", "anunciantes", "profesionales"],
      tamano: "alto",
      precio: "Valor 3",
      nombre: "Estudio del Km 30",
      tipo: "Módulo alto",
      ejemplo: true,
      grafico: true,
      marcaCorta: "EK",
      lema: "Ejemplo · Sourdeaux",
      titulo: "Familia, laboral y sucesiones",
      items: ["Jubilaciones y pensiones", "Alimentos y divorcio", "Contratos", "Posesión de vivienda"],
      texto: "Familia, laboral y sucesiones. Un recuadro alto para matrícula y lista de temas.",
      dato: "Ejemplo · Adolfo Sourdeaux",
    },
    {
      id: "farmacia-alvarez",
      slot: "portada",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "doble",
      precio: "Valor 4",
      nombre: "Farmacia Álvarez",
      tipo: "Media página",
      grafico: true,
      marcaCorta: "FA",
      lema: "En Rosario desde 1961",
      titulo: "Obras sociales, medicamentos y ortopedia",
      items: ["Obras sociales", "Medicamentos y perfumería", "Ortopedia", "Consulta en el local"],
      texto: "Obras sociales, medicamentos, perfumería y ortopedia. En Rosario desde 1961.",
      dato: "Rosario 4605",
      tel: "11 4748-1868",
    },
    {
      id: "vacante-alto",
      slot: "profesionales",
      mosaico: ["clasificados", "anunciantes", "profesionales"],
      tamano: "alto",
      precio: "Valor 3",
      nombre: "Espacio libre",
      tipo: "Módulo alto",
      vacante: true,
      grafico: true,
      marcaCorta: "TU",
      marca: "Tu estudio",
      lema: "Módulo alto · Valor 3",
      titulo: "Lista de trámites o matrícula",
      items: ["Más texto", "Una columna", "Dos filas"],
      texto: "Columna doble de alto. Ideal para estudio, gestoría o listado de trámites.",
      cta: "Reservar módulo alto",
    },
    {
      id: "dental-ar",
      slot: "profesionales",
      mosaico: ["clasificados", "anunciantes", "profesionales"],
      tamano: "simple",
      precio: "Valor 2",
      nombre: "Dental Ar Sourdeaux",
      tipo: "Módulo 1/4",
      grafico: true,
      marcaCorta: "DA",
      lema: "Rosario 4680",
      titulo: "Odontología integral",
      items: ["Implantes y prótesis", "Ortodoncia", "Atención a niños"],
      texto: "Odontología integral en Rosario 4680.",
      tel: "11 6206-3510",
    },
    {
      id: "vacante-cuadrado",
      slot: "portada",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "cuadrado",
      precio: "Valor 5",
      nombre: "Espacio libre",
      tipo: "1/2 alto",
      vacante: true,
      grafico: true,
      marcaCorta: "TU",
      marca: "Tu marca",
      lema: "Este tamaño se reserva",
      titulo: "Tu aviso gráfico, como Servi-Net",
      items: ["Logo y servicios", "Teléfono a la vista", "Arte de la revista o el tuyo"],
      texto: "El mismo tamaño que el aviso gráfico. Arte propio o diseño de la revista.",
      cta: "Reservar 1/2 alto",
    },
    {
      id: "bulonera",
      slot: "comercios",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "simple",
      precio: "Valor 2",
      nombre: "Ferretería Bulonera",
      tipo: "Módulo 1/4",
      grafico: true,
      marcaCorta: "FB",
      lema: "Sobre Rosario",
      titulo: "Ferretería y bulonería",
      items: ["Bulonería", "Delivery publicado"],
      texto: "Ferretería y bulonería sobre Rosario.",
      dato: "Rosario 4635",
      tel: "11 2417-2566",
    },
    {
      id: "clases-derqui",
      slot: "clasificados",
      mosaico: ["clasificados", "anunciantes", "profesionales"],
      tamano: "simple",
      precio: "Valor 2",
      nombre: "Apoyo escolar en Derqui",
      tipo: "Módulo 1/4",
      ejemplo: true,
      grafico: true,
      marcaCorta: "AE",
      lema: "Ejemplo · sin reserva",
      titulo: "Primaria y secundaria",
      items: ["Apoyo por materia", "Horario a convenir"],
      texto: "Primaria y secundaria. Un aviso inventado para mostrar el 1/4.",
      dato: "Ejemplo · Derqui",
    },
    {
      id: "hospital-vet",
      slot: "actualidad",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "doble",
      precio: "Valor 4",
      nombre: "Hospital Veterinario",
      tipo: "Media página",
      grafico: true,
      marcaCorta: "HV",
      lema: "Junto a la estación",
      titulo: "Clínica, imágenes e internación",
      items: ["Consultas de lunes a viernes", "Guardia de fin de semana", "Imágenes"],
      texto: "Clínica, imágenes e internación junto a la estación.",
      dato: "Luis Espinosa 1760",
      tel: "11 4748-9159",
    },
    {
      id: "contadora-ejemplo",
      slot: "profesionales",
      mosaico: ["anunciantes", "profesionales"],
      tamano: "simple",
      precio: "Valor 2",
      nombre: "Contadora de Rosario",
      tipo: "Módulo 1/4",
      ejemplo: true,
      texto: "Monotributo, sueldos e ingresos brutos. Pieza de muestra.",
      dato: "Ejemplo · Km 30",
    },
    {
      id: "electricidad-lopez",
      slot: "comercios",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "simple",
      precio: "Valor 2",
      nombre: "Electricidad López",
      tipo: "Módulo 1/4",
      grafico: true,
      marcaCorta: "EL",
      lema: "Derqui 1015",
      titulo: "Materiales eléctricos",
      items: ["Cables e iluminación", "A metros de la estación"],
      texto: "Materiales eléctricos sobre Derqui.",
      tel: "11 4741-4757",
    },
    {
      id: "frio-barrio",
      slot: "clasificados",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "doble",
      precio: "Valor 4",
      nombre: "Frío del barrio",
      tipo: "Media página",
      ejemplo: true,
      grafico: true,
      marcaCorta: "FB",
      lema: "Ejemplo · no es un comercio real",
      titulo: "Instalación y service de aire",
      items: ["Split e inverter", "Carga de gas", "Mantenimiento"],
      texto: "Instalación y service de aire. Aviso de ejemplo, no es un comercio real.",
      dato: "Ejemplo · Sourdeaux",
    },
    {
      id: "carniceria-mini",
      slot: "clasificados",
      mosaico: ["clasificados"],
      tamano: "mini",
      precio: "Valor 1",
      nombre: "Carnicería La Amistad",
      tipo: "Mini",
      grafico: true,
      marcaCorta: "CA",
      lema: "Sobre Winter",
      titulo: "Entrega en el día",
      texto: "Sobre Winter, entrega en el día.",
      tel: "11 2446-8211",
    },
    {
      id: "alquilo-ejemplo",
      slot: "clasificados",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "doble",
      precio: "Valor 4",
      nombre: "Alquilo en Rosario",
      tipo: "Media página",
      ejemplo: true,
      grafico: true,
      marcaCorta: "AL",
      lema: "Clasificado de ejemplo",
      titulo: "Dos ambientes cerca de la estación",
      items: ["Sin expensas publicadas", "Consultar requisitos", "No es un aviso real"],
      texto: "Ejemplo de clasificado en formato banner.",
      dato: "Ejemplo · Km 30",
    },
    {
      id: "vacante-mini-1",
      slot: "clasificados",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "mini",
      precio: "Valor 1",
      nombre: "Alquilo / vendo",
      tipo: "Mini",
      vacante: true,
      texto: "El recuadro más accesible.",
      cta: "Publicar mini",
    },
    {
      id: "vacante-mini-2",
      slot: "clasificados",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "mini",
      precio: "Valor 1",
      nombre: "Busco empleado",
      tipo: "Mini",
      vacante: true,
      texto: "Empleo o servicio. 40 palabras.",
      cta: "Publicar mini",
    },
    {
      id: "vacante-mini-3",
      slot: "clasificados",
      mosaico: ["clasificados"],
      tamano: "mini",
      precio: "Valor 1",
      nombre: "Se busca",
      tipo: "Mini",
      vacante: true,
      texto: "Clasificado de vidriera.",
      cta: "Publicar mini",
    },
    {
      id: "vacante-simple",
      slot: "comercios",
      mosaico: ["clasificados", "anunciantes", "profesionales"],
      tamano: "simple",
      precio: "Valor 2",
      nombre: "Espacio libre",
      tipo: "Módulo 1/4",
      vacante: true,
      texto: "Un cuarto de página para un local o consultorio.",
      cta: "Reservar 1/4",
    },
    {
      id: "vacante-doble",
      slot: "portada",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "doble",
      precio: "Valor 4",
      nombre: "Espacio libre",
      tipo: "Media página",
      vacante: true,
      texto: "Dos columnas. Más lugar para foto y horario.",
      cta: "Reservar media página",
    },
    {
      id: "planos-ejemplo",
      slot: "profesionales",
      mosaico: ["anunciantes", "profesionales"],
      tamano: "simple",
      precio: "Valor 2",
      nombre: "Planos y obra",
      tipo: "Módulo 1/4",
      ejemplo: true,
      texto: "Planos municipales y documentación. Solo para mostrar el formato.",
      dato: "Ejemplo · Malvinas",
    },
    {
      id: "vacante-banner",
      slot: "portada",
      mosaico: ["clasificados", "anunciantes"],
      tamano: "banner",
      precio: "Valor 6",
      nombre: "Espacio libre",
      tipo: "Banner de página",
      vacante: true,
      grafico: true,
      marcaCorta: "TU",
      marca: "Tu banner",
      lema: "Fila completa · Valor 6",
      titulo: "El aviso más visible de la grilla",
      items: ["Logo y servicios", "Teléfono y web", "Se ve al abrir Clasificados"],
      texto: "La fila completa. El espacio de más valor, al pie de la grilla.",
      cta: "Reservar banner",
    },
    {
      id: "actualidad-libre",
      slot: "actualidad",
      nombre: "Tu aviso en Actualidad",
      tipo: "Módulo 1/4",
      tamano: "simple",
      precio: "Valor 2",
      vacante: true,
      texto: "Al lado de las notas del barrio y de Malvinas.",
      cta: "Anunciar en Actualidad",
    },
    {
      id: "agenda-libre",
      slot: "eventos",
      mosaico: ["anunciantes"],
      tamano: "simple",
      precio: "Valor 2",
      nombre: "Tu aviso en la Agenda",
      tipo: "Módulo 1/4",
      vacante: true,
      texto: "Sponsor de feria, club o salón.",
      cta: "Anunciar en Agenda",
    },
  ],
};
